### ISSUE TITLE
Checklist for bringing first version of decomp.me online

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#15]
decomp.me code:
(deferred till next version)
* ~~Better parameter validation (make sure things look sane, aren't too large)~~
* ~~Limit API calls by IP and session~~
* ~~Think about security and sandboxing~~

Server:
- [x] Follow django production checklist
- [x] Set up postgresql on webserver
- [x] Set up nginx on webserver
